In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import nltk
import seaborn as sns
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer
from wordcloud import WordCloud
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [ ]:
df = pd.read_csv("./encoded-sms-spam.csv")
# ctrl + enter = execute cells
#alt + enter = execute + create cell

In [ ]:
df.head()

result                                              input  count characters  \
0      0  Go until jurong point, crazy.. Available only ...               111   
1      0                      Ok lar... Joking wif u oni...                29   
2      1  Free entry in 2 a wkly comp to win FA Cup fina...               155   
3      0  U dun say so early hor... U c already then say...                49   
4      0  Nah I don't think he goes to usf, he lives aro...                61   

   count words  count sentence  \
0           24               2   
1            8               2   
2           37               2   
3           13               1   
4           15               1   

                                           processed  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4               nah think goe usf live around though

In [ ]:
df.tail()

In [ ]:
df.sample(10)

In [ ]:
df.columns
#to delete columns - drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace = True)

In [ ]:
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace = True)

In [ ]:
df.head()

In [ ]:
df.rename(columns={'v1':'result','v2':'input'},inplace=True)

In [ ]:
df.head()

In [ ]:
df['result'].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

In [ ]:
df.shape

In [ ]:
import matplotlib.pyplot as plt
plt.pie(df['result'].value_counts(),labels=['not spam','spam'],autopct='%0.2f')
plt.show()

In [ ]:
import nltk

In [ ]:
nltk.download('all')

In [ ]:
df.head()

In [ ]:
pd.set_option('future.no_silent_downcasting', True)
df.replace({'ham': 0, 'spam': 1}, inplace=True)


In [ ]:
df.head()

In [ ]:
nltk.download('punkt')

In [ ]:
df['count characters'] = df['input'].apply(len)
df['count words'] = df['input'].apply(lambda i:len(nltk.word_tokenize(i)))
#'word_tokenize' function takes a string of text as input and returns a list of words
df['count sentence'] = df['input'].apply(lambda i:len(nltk.sent_tokenize(i)))
#'sent_tokenize' function takes a string of text as input and returns a list of sentences

In [ ]:
df.head()

In [ ]:
df[['count characters','count words','count sentence']].describe()

In [ ]:
df[df['result'] == 0][['count characters', 'count words', 'count sentence']].describe()

In [ ]:
df[df['result'] == 1][['count characters', 'count words', 'count sentence']].describe()

In [ ]:
#for better visualization, we will plot a histogram using 'seaborn'
plt.figure(figsize = (15, 5))
sns.histplot(df[df['result'] == 0]['count characters'], color = "yellow")
sns.histplot(df[df['result'] == 1]['count characters'], color = "black")


In [ ]:
plt.figure(figsize = (15, 5))
sns.histplot(df[df['result'] == 0]['count words'], color = "yellow")
sns.histplot(df[df['result'] == 1]['count words'], color = "black")

In [ ]:
#finding relationship between the columns
sns.pairplot(df, hue='result')

In [ ]:
nltk.download('stopwords')

In [ ]:
from nltk.tokenize import word_tokenize


In [ ]:
def transform_text(text):
  text = text.lower()

  #tokenization
  text = word_tokenize(text)

  #removing special characters
  removedSC = list()
  for i in text:
      if i.isalnum():
          removedSC.append(i)

  text = removedSC[:]

  #removing stop words and punctuation characters
  removedSWPC = list()
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
            removedSWPC.append(i)

  text = removedSWPC[:]

  ps = PorterStemmer()
  stemmed = list()
  for i in text:
      stemmed.append(ps.stem(i))
  text = stemmed[:]
  return " ".join(text)

In [ ]:
df['processed'] = df['input'].apply(transform_text)

df.head()

result                                              input  count characters  \
0      0  Go until jurong point, crazy.. Available only ...               111   
1      0                      Ok lar... Joking wif u oni...                29   
2      1  Free entry in 2 a wkly comp to win FA Cup fina...               155   
3      0  U dun say so early hor... U c already then say...                49   
4      0  Nah I don't think he goes to usf, he lives aro...                61   

   count words  count sentence  \
0           24               2   
1            8               2   
2           37               2   
3           13               1   
4           15               1   

                                           processed  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4               nah think goe usf live around though

In [ ]:
#will be creating word cloud for data visualization to display the most frequently occurring words in the processed dataset.
#using 'WordCloud' class

wc = WordCloud(width=500, height=500, min_font_size=10, background_color='white')

In [ ]:
#creating a wordcloud for the SPAM messages
spamWC = wc.generate(df[df['result'] == 1]['processed'].str.cat(sep=" "))

#creating figure and displaying
plt.figure(figsize=(12, 6))
plt.imshow(spamWC)

In [ ]:
#creating a wordcloud for the not SPAM messages
spamWC = wc.generate(df[df['result'] == 0]['processed'].str.cat(sep=" "))

#creating figure and displaying
plt.figure(figsize=(12, 6))
plt.imshow(spamWC)

In [ ]:
#extracting all the words used in SPAM messages
spamWords = list()

for msg in df[df['result'] == 1]['processed'].tolist():
  for word in msg.split():
    spamWords.append(word)

spamWords

In [ ]:
#to count the frequency of the words, we will be using the Counter class to create a dictionary
spamWordsDictionary = Counter(spamWords)

#to extract the most common words
spamWordsDictionary.most_common(40)

In [ ]:
#converting this dictionary to a dataframe
mostCommonSPAM = pd.DataFrame(spamWordsDictionary.most_common(40))

In [ ]:
plt.figure(figsize=(12, 6))
sns.barplot(data = mostCommonSPAM, x=0, y=1)
plt.xticks(rotation='vertical')
plt.show()

In [ ]:
#converting the collection of text into a matrix of token counts
cv = CountVectorizer()

In [ ]:
#transforming the data of processed column
X = cv.fit_transform(df['processed']).toarray()

#printing size of X
X.shape

(5169, 6708)

In [ ]:
#storing the values of the 'result' column
y = df['result'].values
y

array([0, 0, 1, ..., 0, 0, 0], dtype=object)

In [ ]:
#splitting the training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 49)

In [ ]:
#creating the objects for the models
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [ ]:
#Convert y to a numpy array with integer type:
y = df['result'].astype(int).values


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=49)


In [ ]:
#training the dataset for GaussianNB
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(precision_score(y_test, y_pred1))

0.8597678916827853
[[775 124]
 [ 21 114]]
0.4789915966386555


In [ ]:
#training the dataset for MultinomialnNB
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))
print(precision_score(y_test, y_pred2))

0.9574468085106383
[[899   0]
 [ 44  91]]
1.0


In [ ]:
#training the dataset for BernoulliNB
bnb.fit(X_train, y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))
print(precision_score(y_test, y_pred3))


0.9642166344294004
[[893   6]
 [ 31 104]]
0.9454545454545454


In [ ]:
#using 'TfidfVectorizer' for vectorization
tf = TfidfVectorizer()

#transforming the data of processed column
X = tf.fit_transform(df['processed']).toarray()

#storing the values of the 'result' column
y = df['result'].values

#splitting the training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 49)

In [ ]:
#training the dataset for GaussianNB
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(precision_score(y_test, y_pred1))

0.8597678916827853
[[775 124]
 [ 21 114]]
0.4789915966386555


In [ ]:
#training the dataset for MultinomialnNB
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))
print(precision_score(y_test, y_pred2))

0.9574468085106383
[[899   0]
 [ 44  91]]
1.0


In [ ]:
#training the dataset for BernoulliNB
bnb.fit(X_train, y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))
print(precision_score(y_test, y_pred3))

0.9642166344294004
[[893   6]
 [ 31 104]]
0.9454545454545454


In [ ]:
#we will pickle 2 files
import pickle
pickle.dump(tf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))